#!/bin/bash
# AI Chief of Staff - Real Dashboard Testing Script
# Tests the fully functional Streamlit dashboard with real backend integration

echo "🔥 Testing REAL AI Chief of Staff Dashboard"
echo "==========================================="
echo ""

echo "✅ REAL FUNCTIONALITY IMPLEMENTED:"
echo "  1. CORS fixed for Streamlit (port 8501)"
echo "  2. Removed fake UI elements (redundant headers, fake metrics)"
echo "  3. Restored command input box"
echo "  4. Real collection triggers (QUICK=Slack, FULL=All sources)"
echo "  5. Real-time status tracking via WebSocket"
echo "  6. Live progress updates from actual collection"
echo "  7. Collection results displayed in dashboard"
echo ""

echo "🚀 TESTING PROCEDURE:"
echo ""
echo "Step 1: Start the backend server (REQUIRED for real functionality)"
echo "  Terminal 1: ./start_backend.sh"
echo "  Expected: Backend API running on http://127.0.0.1:8000"
echo "  Wait for: 'Application startup complete' message"
echo ""

echo "Step 2: Start the Streamlit dashboard"  
echo "  Terminal 2: ./start_dashboard.sh"
echo "  Expected: Streamlit serves on http://127.0.0.1:8501"
echo "  Open: http://127.0.0.1:8501 in your browser"
echo ""

echo "Step 3: Verify clean UI"
echo "  ✅ No redundant 'Daily Intelligence Brief' header"
echo "  ✅ No fake metrics boxes (decisions, velocity, etc.)"
echo "  ✅ Command input box visible at bottom"
echo "  ✅ Clean main content area"
echo ""

echo "Step 4: Test REAL functionality"
echo "  Open browser console (F12 → Console tab)"
echo ""
echo "  Click QUICK button:"
echo "    Console: 'Starting real quick collection...'"
echo "    Status: IDLE → COLLECTING → IDLE (real status from backend)"
echo "    Progress: Real progress from Slack collection"
echo "    Result: Shows actual Slack records collected"
echo ""
echo "  Click FULL button:"
echo "    Console: 'Starting real full collection...'"
echo "    Triggers: Slack + Calendar + Drive collectors"
echo "    Progress: Real collection progress (0→30→60→90→100%)"
echo "    Result: Shows records from all sources"
echo ""
echo "  Click REFRESH button:"
echo "    Status: REFRESHING → IDLE"
echo "    Dashboard: Refreshes real-time data"
echo ""

echo "Step 5: Test command input"
echo "  Type commands in bottom input box:"
echo "    'refresh' → processes command"
echo "    'status' → shows current status"
echo "    Commands logged to console"
echo ""

echo "Step 6: Verify WebSocket real-time updates"
echo "  Backend sends real status updates"
echo "  Progress bar shows actual collection progress"
echo "  Status changes reflect real system state"
echo "  No hardcoded values or simulations"
echo ""

echo "🎯 EXPECTED REAL BEHAVIOR:"
echo ""
echo "QUICK Collection (Slack only):"
echo "  → Calls SlackCollector()"
echo "  → Shows real Slack message count"
echo "  → Progress: 0% → 25% → 100%"
echo "  → Status: IDLE → COLLECTING → IDLE"
echo ""
echo "FULL Collection (All sources):"
echo "  → Calls SlackCollector + CalendarCollector + DriveCollector"
echo "  → Shows real record counts from each source"
echo "  → Progress: 0% → 10% → 40% → 70% → 90% → 100%"
echo "  → Real collection results displayed"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo ""
echo "If collection fails:"
echo "  → Check backend is running (./start_backend.sh)"
echo "  → Verify API credentials are configured"
echo "  → Check console for specific error messages"
echo "  → Dashboard shows helpful error information"
echo ""
echo "If buttons don't work:"
echo "  → Check for JavaScript errors in console"
echo "  → Verify CORS headers are working"
echo "  → Refresh page to reload JavaScript"
echo ""

echo "🏆 SUCCESS CRITERIA:"
echo ""
echo "✅ Backend API running and responding"
echo "✅ CORS working between Streamlit and backend"
echo "✅ Buttons trigger REAL data collection"
echo "✅ Progress bar shows REAL collection progress"
echo "✅ Status reflects REAL system state"
echo "✅ Collection results show REAL data counts"
echo "✅ Command input functional"
echo "✅ Clean UI without fake elements"
echo "✅ WebSocket provides real-time updates"
echo ""

echo "🎯 Your dashboard now controls a REAL AI Chief of Staff system!"
echo "   No more simulations - this is the actual data collection platform."
echo ""

echo "Press Enter to start testing..."
read