# Calendar Availability Targets Configuration
# List of users to monitor for calendar availability

# Configuration metadata
collection_schedule: "daily"
retention_days: 30
rate_limit: 1  # requests per second max for freebusy API
lookahead_days: 7

# Target users for availability monitoring
# Format: email addresses that have calendar access permissions
users:
  # Executive tier - highest priority
  - david.campos@biorender.com
  - kiran.rao@biorender.com
  - ryan@biorender.com  # CEO
  - shiz@biorender.com  # CTO
  
  # Department heads - second priority
  - adam@biorender.com
  - charlie@biorender.com
  - mark@biorender.com
  - philip@biorender.com
  
  # Key stakeholders - third priority
  - jon.fan@biorender.com
  - meghana.reddy@biorender.com
  - angel@biorender.com
  - chris.hemberger@biorender.com

# Calendar API settings
calendar_api:
  service: "calendar"
  version: "v3"
  endpoint: "freebusy"
  
  # Rate limiting (Google Calendar API Tier 1)
  requests_per_second: 1
  requests_per_minute: 20
  retry_attempts: 3
  backoff_base: 2

# Output configuration
output:
  directory: "data/state"
  filename: "calendar_availability.json"
  format: "json"
  include_metadata: true
  
# Error handling
error_handling:
  continue_on_403: true  # Continue if some calendars deny access
  continue_on_404: true  # Continue if some calendars not found
  log_errors: true
  max_consecutive_failures: 5